services:
  cloudflare-ddns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "cloudflare-ddns"
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      - PROXIED=true
      - PUID=1000
      - PGID=1000
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
